services:
  sticker-bot:
    build: .
    container_name: telegram-sticker-bot
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    dns_opt:
      - timeout:2
      - attempts:3
      - rotate
    env_file:
      - .env
    volumes:
      - bot_data:/data
      - bot_temp:/tmp/sticker-bot

volumes:
  bot_data:
  bot_temp:
